### PR TITLE
Add frontend convenient functions

### PR DESCRIPTION
**Pull request by tk3369**
Haikal's request made me think about how TypeDBClient.jl would be used. So I have added a few "frontend" functions. An example can be found in examples/my-typedb.jl:

```julia
dbconnect("127.0.0.1") do client
    open(client, "my-typedb") do session
        write(session) do transaction
            insert(transaction, raw"insert $_ isa person;")
        end
        read(session) do transaction
            answers = match(transaction, raw"match $p isa person;")
        end
    end
end
```

@FrankUrbach @mkschulze - what do you think about this API?

Notes:
- I thought about extending `Base.connect` but that actually does not exist in Base 😝 
- I think extending `Base.open`, `Base.read`, and `Base.write` seems reasonable for this use case
- `close(::AbstractCoreClient)` does not exist yet... @FrankUrbach can you check?

Cc: @haikalpribadi @alexjpwalker

### CODE REVIEW

**Comment by mkschulze** [comment]
Frank implemented it like this in BDD

```julia
g = TypeDBClient

@given("connection has been opened") do context
    client = g.CoreClient("127.0.0.1",1729)
    context[:client] = client
end
```

This makes sense to me, given that we might add g.ClusterClient("IP",Port) as well.

Let's see what @FrankUrbach thinks.

**Comment by alexjpwalker** [comment]
Structure looks good to me. What is dbconnect? I would expect this to be called something like `TypeDBClient`

**Comment by FrankUrbach** [comment]
>.... What is dbconnect? ...
dbconnect is a function which is more commonly used in the Julia world to connect to any database.

**Comment by FrankUrbach** [comment]
Added the requested close function for the client.

**Review by FrankUrbach — APPROVED** [review]

**Comment by FrankUrbach** [comment]
LGTM

**Pull request merged**
